### ISSUE TITLE
Placing a drain without the mod enabled breaks the game

### ISSUE THREAD

**Issue by RenaKunisaki** [yenyang/rainfall#2]
Try placing a storm drain with the mod turned off, and watch the flood of both water and NullReferenceException errors.

**Comment by yenyang** [comment]
That’s a user issue, I can’t design for people not having the mod on.

**Comment by RenaKunisaki** [comment]
That's fair, but there should be some warning if it can't be avoided. I assumed the drain would either still help with flood water, or just do nothing, not break the game entirely.

Maybe the assets can be hidden by default, and the mod make them visible at startup?

**Comment by yenyang** [comment]
You don't seem to understand that I have no control over what the user does with the asset if the mod isn't enabled. The mod is the only way I can implement any code. The mod is listed as a dependency for the asset. That is the warning. This mod and the assets have been on the workshop for years and nobody has complained about this issue.
